import { Inter } from "next/font/google";
import "../styles/globals.scss";
import {
  Allura,
  Roboto_Mono,
  Londrina_Outline,
  Lemonada,
  Montserrat_Alternates,
} from "next/font/google";
import TopNavBar from "@/components/frontend/TopNavBar";
import Script from "next/script";
const allura = Allura({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-allura",
});
const montserrat_Alternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Montserrat_Alternates",
});
const lemonada = Lemonada({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lemonada",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-roboto-mono",
});
const londrinaoutline = Londrina_Outline({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-londrina-outline",
});

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script id='google-analytics'>
       {`  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9J6HVY4E09');`}
      </Script>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-9J6HVY4E09"></Script></head>
            
              <meta name="description" content="Generated by create next app" />

      <body
        className={`${allura.variable} ${montserrat_Alternates.variable} ${robotoMono.variable} ${londrinaoutline.variable}  ${lemonada.variable}`}
      >
        {children}
      </body>

      
    </html>
  );
}
