import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { Allura, Roboto_Mono , Londrina_Outline} from "next/font/google";


const allura = Allura({ subsets: ["latin"], weight:['400'], variable:'--font-allura' });
const robotoMono = Roboto_Mono({ subsets: ["latin"], weight:['400'], variable:'--font-roboto-mono' });
const londrinaoutline = Londrina_Outline({ subsets: ["latin"], weight:['400'], variable:'--font-londrina-outline' });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${allura.variable} ${robotoMono.variable} ${londrinaoutline.variable}`}>{children}</body>
    </html>
  );
}
